# Generated by Django 2.1 on 2021-04-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestJKZDH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_home_href',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('href', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
